[package]
name = "bevy_dialogue_system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
bevy_editor_pls = "0.7.0"
itertools = "0.12.1"
